spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    openfeign:
      okhttp:
        enabled: true
  thymeleaf:
    cache: false



jwt:
  secret: W6pd5KQixwxUdMZLQou52w44YxmxZBcDf8Ctk2GqsNxZW4ySqRw3ph6RMAE0p2Xh
  access-token-expiration: 3600
  refresh-token-expiration: 86400

